name=Adafruit Marquee
version=1.0.0
author=Adafruit
maintainer=Adafruit <info@adafruit.com>
sentence=Adafruit Marquee Client
paragraph=Adafruit Marquee Client for Arduino.
category=Display
url=https://github.com/adafruit/Adafruit_Marquee
architectures=*
depends=Adafruit GFX Library, Adafruit EPD, ArduinoJson, Adafruit SPIFlash, SdFat - Adafruit Fork, Adafruit TinyUSB Library, base64, Adafruit ImageReader Library, Adafruit MQTT Library