; PlatformIO project for local development of the Adafruit Marquee library.

[platformio]
src_dir = examples/marquee_simpletest
default_envs = magtag

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_type = debug

; src/ is compiled straight into the example rather than being listed as a lib_deps entry.
build_src_filter = +<*> +<../../src/>
build_flags =
	-Wall
	-I$PROJECT_DIR/src

lib_deps =
	WiFi
	NetworkClientSecure
	adafruit/Adafruit SPIFlash
	adafruit/Adafruit TinyUSB Library
	bblanchon/ArduinoJson
	adafruit/Adafruit ImageReader Library
	densaugeo/base64
    robtillaart/CRC
	; Local fork
	symlink://../Adafruit_MQTT_Library
    symlink://../Adafruit_EPD

lib_ignore =
	WiFiNINA
	WiFiNINA_-_Adafruit_Fork
	WiFi101

lib_compat_mode = strict

[env:magtag]
board = adafruit_magtag29_esp32s2
board_build.filesystem = littlefs

[env:adafruit_feather_esp32s3]
board = adafruit_feather_esp32s3
board_build.filesystem = littlefs

[env:x4pro]
board = esp32-s3-devkitc1-n16r8
board_build.mcu = esp32s3
board_build.flash_mode = dio
board_build.arduino.memory_type = dio_opi
board_build.partitions = tinyuf2-xteink4-pro-uc8279.csv
build_flags =
  ${env.build_flags}
  ; Use TinyUSB CDC for serial
  -DARDUINO_USB_MODE=0
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MSC_ON_BOOT=0
  -DARDUINO_USB_DFU_ON_BOOT=0
  -DUSB_MANUFACTURER=\"Marquee\"
  -DUSB_PRODUCT=\"Marquee_X4_Pro\"
  -DBOARD_HAS_PSRAM
  -DCORE_DEBUG_LEVEL=3
  ; Not defined within Arduino/ESP32 core, board is a "default"
  -DMARQUEE_BOARD_XTEINK_X4_PRO
  -std=gnu++2a
build_unflags =
  -std=gnu++11